### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by pwatts6060** [Chris-Bitler/Runelite-StealingArtefacts#7]
`java.lang.NullPointerException: Cannot invoke "net.runelite.api.coords.WorldPoint.getX()" because "position" is null
	at io.cbitler.stealingartefacts.StealingArtefactsPlugin.isInPisc(StealingArtefactsPlugin.java:322)
	at io.cbitler.stealingartefacts.StealingArtefactsPlugin.onGameTick(StealingArtefactsPlugin.java:153)`

Just logged in while testing a different plugin and saw this in the console.

**Comment by Chris-Bitler** [comment]
Should be fixed once https://github.com/runelite/plugin-hub/pull/3066 is merged
